Structure Change - Split functions into their own files
IT-Minds-opensource/ts-array-ext pull request #20
Opened 2020-10-16 10:50 UTC by JeppeTrip

Fixes #17 .
Moved the array extensions into their individual files.

2020-10-16 11:46 UTC, objmj-itminds commented
The types.ts file should after a successful migration can be deleted.

Also. Can the utils files such as be moved into a utils dir?

2020-10-16 12:55 UTC, JeppeTrip commented
> Also. Can the utils files such as be moved into a utils dir?

What utils files should be moved into the utils directory ?

2020-10-17 11:24 UTC, objmj-itminds commented
> What utils files should be moved into the utils directory ?
customErrors.ts 
typeGuards.ts

2020-10-17 11:28 UTC, objmj-itminds requested changes
There is a difference in the way the typing is handled per file.
Some use 
```typescript
declare global { 
...
}
``` 

Other do not.
If this is on purpose please leave a comment in the code explaining the use.

2020-10-19 07:15 UTC, JeppeTrip commented
> 
> 
> There is a difference in the way the typing is handled per file.
> Some use
> 
> ```ts
> declare global { 
> ...
> }
> ```
> 
> Other do not.
> If this is on purpose please leave a comment in the code explaining the use.

I have added an explanation to some of the relevant files. 
The reason is basically that TS defines a module as any file with and import or export statement. TS furthermore scopes their modules and for us to modify a type (such as Array) existing in the global scope we have to declare our module as being in the global scope. 
Files without import or export statements are treated as scripts in the global scope and it is therefor not required (and not possible due to TS) to declare it being in the global scope, since it already exists there.
https://www.typescriptlang.org/docs/handbook/modules.html
https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-modifying-module-d-ts.html

2020-10-19 08:51 UTC, objmj-itminds commented
We have discussed using directories for the move
```
/
- src/
- - sum/
- - - index.ts
- - - README.md
- - average/
- - - index.ts
- - - README.md
```

2020-10-19 10:05 UTC, objmj-itminds approved these changes
I will create some other chores to add details in each README but I like this. 
I think we need to prio this PR so the others can get to target the changes made from this.

2020-10-19 10:05 UTC, objmj-itminds commented on tsconfig.json
> +  "include": ["src/**/*.ts", "src/utils/typeGuards.ts", "src/utils/customErrors.ts"],
The added cases are covered by the first statement. Might be an editor suggestion.

2020-10-19 10:45 UTC, merged