Added export and global declarations.
IT-Minds-opensource/ts-array-ext pull request #31
Opened 2020-10-26 10:36 UTC by JeppeTrip

# Description

Fixes #29.
Added the export statement and global scope declarations to the necessary files. 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Ran and passed the mandatory test suites.

# Checklist:

Fill out the checklist using [✔️]

- [✔️] My code follows the style guidelines of this project
- [✔️] I have performed a self-review of my own code
- [✔️] I have commented my code, particularly in hard-to-understand areas
- [✔️] I have made corresponding changes to the documentation
- [✔️] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [✔️] New and existing unit tests pass locally with my changes
- [✔️] Any dependent changes have been merged and published in downstream modules

2020-10-26 11:21 UTC, objmj-itminds requested changes

2020-10-26 11:21 UTC, objmj-itminds commented on src/sortByAttr/index.ts
> +  type SortDirection = "ASC" | "DESC";
Don't think this line should be under the global scope.

2020-10-26 11:44 UTC, objmj-itminds approved these changes

2020-10-27 11:48 UTC, phillip-itminds approved these changes

2020-10-27 12:06 UTC, merged